######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 25 15:18:22 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += centralwidg.h guiplayer.h mainWindow.h playergui.h tempPlayer.h
SOURCES += centralwidg.cpp \
           guiplayer.cpp \
           mainWindow.cpp \
           playergui.cpp \
           tempGame.cpp \
           tempPlayer.cpp
