######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 02:08:43 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += action.h \
           bank.h \
           card1.h \
           card2.h \
           centralwidg.h \
           game_board.h \
           guiplayer.h \
           mainWindow.h \
           moveAction.h \
           player.h \
           playergui.h \
           space.h \
           startWindow.h
SOURCES += action.cpp \
           bank.cpp \
           card1.cpp \
           card2.cpp \
           centralwidg.cpp \
           game_board.cpp \
           guiplayer.cpp \
           mainWindow.cpp \
           moveAction.cpp \
           pa6.cpp \
           player.cpp \
           playergui.cpp \
           space.cpp \
           startWindow.cpp
