######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 15 15:21:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += world.cpp
